[package]
name = "logisim"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
egui = "0.28.1"
egui-macroquad = "0.15.0"
macroquad = "0.4.12"
petgraph = "0.6.5"
phf = { version = "0.11.2", features = ["macros"] }
